---
application:
  name: "dashboard-api"
  project: "plubin"
  organization: "QoveryCommunity"
routers:
- name: "main-dashboard-api"
  routes:
  - application_name: "dashboard-api"
    paths:
    - "/*"
